[project]
name = "video-edit-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "mcp[cli]>=1.9.0",
    "pillow>=11.2.1",
    "pytest>=8.3.5",
]
